use crate::analysis::control_flow_facts::{decode_memory_context_for, function_max_bytes};
use fission_analysis_db::{FactSource, ProgramSnapshot, SymbolKind};
use fission_loader::loader::LoadedBinary;
use fission_loader::loader::types::{
    DwarfFunctionInfo, InferredFieldInfo, InferredTypeInfo, PdbFunctionInfo,
};
use fission_pcode::midend::cspec::register_model_for_language;
use fission_signatures::FidDatabaseSet;
use fission_sleigh::runtime::{DecodeContract, RuntimeSleighFrontend};
use std::collections::HashMap;
use std::sync::Arc;

/// Generous upper bound on a single function's instruction count for FID
/// hashing -- mirrors `fission_decompiler::fid`'s decode safety valve, not a
/// tuning knob.
const FID_INSTRUCTION_LIMIT: usize = 4000;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum FactProvenance {
    UserRename,
    BinarySymbol,
    ImportExport,
    StrongFid,
    WeakAutogenerated,
    PdbMetadata,
    NativeMetadata,
    LoaderMetadata,
    DebugInfo,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct NameFact {
    pub name: String,
    pub provenance: FactProvenance,
}

#[derive(Debug, Clone)]
pub struct TypeFact {
    pub info: InferredTypeInfo,
    pub provenance: FactProvenance,
}

#[derive(Debug, Clone)]
pub struct FunctionFacts {
    pub address: u64,
    pub chosen_name: Option<NameFact>,
    pub name_facts: Vec<NameFact>,
    pub type_facts: Vec<TypeFact>,
    pub dwarf_info: Option<DwarfFunctionInfo>,
    pub pdb_info: Option<PdbFunctionInfo>,
    pub structuring_hints: Option<fission_midend_core::NirFunctionHints>,
    pub calling_convention: Option<fission_core::CallingConvention>,
}

impl FunctionFacts {
    pub fn dwarf_type_fact_count(&self) -> usize {
        let Some(info) = self.dwarf_info.as_ref() else {
            return 0;
        };
        info.params.len() + info.local_vars.len() + usize::from(info.return_type.is_some())
    }

    pub fn pdb_type_fact_count(&self) -> usize {
        let Some(info) = self.pdb_info.as_ref() else {
            return 0;
        };
        info.params.len() + info.local_vars.len() + usize::from(info.return_type.is_some())
    }

    pub fn native_type_fact_count(&self) -> usize {
        self.type_facts
            .iter()
            .filter(|fact| fact.provenance == FactProvenance::NativeMetadata)
            .count()
    }

    pub fn loader_type_fact_count(&self) -> usize {
        self.type_facts
            .iter()
            .filter(|fact| fact.provenance == FactProvenance::LoaderMetadata)
            .count()
    }
}

#[derive(Debug, Clone)]
pub struct FactStore {
    program: Arc<ProgramSnapshot>,
    name_facts: HashMap<u64, Vec<NameFact>>,
    native_type_facts: HashMap<u64, Vec<InferredTypeInfo>>,
    loader_type_facts: Arc<Vec<InferredTypeInfo>>,
    dwarf_functions: Arc<HashMap<u64, DwarfFunctionInfo>>,
    pdb_functions: Arc<HashMap<u64, PdbFunctionInfo>>,
    structuring_hints: HashMap<u64, fission_midend_core::NirFunctionHints>,
    pub calling_conventions: HashMap<u64, fission_core::CallingConvention>,
}

impl Default for FactStore {
    fn default() -> Self {
        Self {
            program: Arc::new(ProgramSnapshot::default()),
            name_facts: HashMap::new(),
            native_type_facts: HashMap::new(),
            loader_type_facts: Arc::new(Vec::new()),
            dwarf_functions: Arc::new(HashMap::new()),
            pdb_functions: Arc::new(HashMap::new()),
            structuring_hints: HashMap::new(),
            calling_conventions: HashMap::new(),
        }
    }
}

impl FactStore {
    pub fn from_binary(binary: &LoadedBinary) -> Self {
        Self::from_program(
            binary,
            Arc::new(ProgramSnapshot::from_loaded_binary(binary)),
        )
    }

    pub fn from_program(binary: &LoadedBinary, program: Arc<ProgramSnapshot>) -> Self {
        let mut store = Self {
            program: Arc::clone(&program),
            name_facts: HashMap::new(),
            native_type_facts: HashMap::new(),
            loader_type_facts: Arc::new(binary.inferred_types.clone()),
            dwarf_functions: Arc::new(binary.dwarf_functions.clone()),
            pdb_functions: Arc::new(binary.pdb_functions.clone()),
            structuring_hints: HashMap::new(),
            calling_conventions: HashMap::new(),
        };

        for function in &program.functions {
            if function.name.trim().is_empty() {
                continue;
            }
            let provenance = if function.is_import || function.is_export {
                FactProvenance::ImportExport
            } else if function.provenance.source == FactSource::DebugInfo {
                FactProvenance::DebugInfo
            } else {
                FactProvenance::BinarySymbol
            };
            store.ingest_name_fact(function.entry, function.name.clone(), provenance);
        }

        for symbol in &program.symbols {
            if !symbol.name.trim().is_empty() {
                let provenance = match symbol.kind {
                    SymbolKind::Import | SymbolKind::Export => FactProvenance::ImportExport,
                    SymbolKind::Function | SymbolKind::Data | SymbolKind::RelocationTarget => {
                        FactProvenance::BinarySymbol
                    }
                };
                store.ingest_name_fact(symbol.address, symbol.name.clone(), provenance);
            }
        }

        for (addr, func) in &binary.pdb_functions {
            if !func.name.trim().is_empty() {
                store.ingest_name_fact(*addr, func.name.clone(), FactProvenance::PdbMetadata);
            }
        }

        store.ingest_signature_matches(binary);

        // Load user-defined renames from sidecar patch file (<binary_name>.fission.json) if it exists
        let sidecar_path = std::path::Path::new(&binary.path).with_extension("fission.json");
        if let Ok(content) = std::fs::read_to_string(&sidecar_path) {
            #[derive(serde::Deserialize)]
            struct SidecarField {
                name: String,
                type_name: String,
                offset: u32,
                size: u32,
            }

            #[derive(serde::Deserialize)]
            struct SidecarStruct {
                name: String,
                size: u32,
                fields: Vec<SidecarField>,
            }

            #[derive(serde::Deserialize)]
            struct SidecarProject {
                #[serde(default)]
                user_function_names: std::collections::HashMap<String, String>,
                #[serde(default)]
                user_structs: Vec<SidecarStruct>,
            }
            if let Ok(sidecar) = serde_json::from_str::<SidecarProject>(&content) {
                for (addr_str, name) in sidecar.user_function_names {
                    let parsed_addr = addr_str.parse::<u64>().ok().or_else(|| {
                        let clean = addr_str.trim_start_matches("0x").trim_start_matches("0X");
                        u64::from_str_radix(clean, 16).ok()
                    });
                    if let Some(addr) = parsed_addr {
                        store.ingest_name_fact(addr, name, FactProvenance::UserRename);
                    }
                }

                for user_struct in sidecar.user_structs {
                    let info = InferredTypeInfo {
                        name: user_struct.name,
                        mangled_name: String::new(),
                        kind: "struct".to_string(),
                        fields: user_struct
                            .fields
                            .into_iter()
                            .map(|f| InferredFieldInfo {
                                name: f.name,
                                type_name: f.type_name,
                                offset: f.offset,
                                size: f.size,
                            })
                            .collect(),
                        size: user_struct.size,
                        metadata_address: 0,
                    };
                    Arc::make_mut(&mut store.loader_type_facts).push(info);
                }
            }
        }

        store
    }

    pub fn program(&self) -> &ProgramSnapshot {
        &self.program
    }

    pub fn program_arc(&self) -> Arc<ProgramSnapshot> {
        Arc::clone(&self.program)
    }

    /// Run exact Ghidra-style FID matching when sufficient decoded instruction
    /// metadata is available.
    ///
    /// The previous prologue byte-pattern matcher is intentionally not used here:
    /// approximate pattern hits must not be promoted to `StrongFid`. Nor is
    /// the older `fission_signatures::fid` hash/decoder pipeline -- it
    /// computed a non-standard digest (byte-order and extra-mixing
    /// deviations from Ghidra's real `FNV1a64MessageDigest`) over a
    /// hand-rolled x86 decoder that never captured register operands at
    /// all, so it could never actually match a real `.fidbf` database's
    /// hashes. Hashing here instead goes through
    /// `fission_sleigh::runtime::RuntimeSleighFrontend::fid_full_hash`,
    /// validated byte-for-byte against real Ghidra 12.0.4 output (see
    /// `PROJECT.md`'s FID entries) -- the same primitive `fission_cli
    /// identify` uses.
    fn ingest_signature_matches(&mut self, binary: &LoadedBinary) {
        // Only support PE/ELF/Mach-O or format specification with x86 architecture for FID matching
        let is_x86 = binary.arch_spec.to_lowercase().contains("x86")
            || binary.arch_spec.to_lowercase().contains("x64")
            || binary.arch_spec.to_lowercase().contains("amd64");
        if !is_x86 {
            return;
        }

        let compiler_id = binary.get_ghidra_compiler_id();
        let db_set = FidDatabaseSet::discover_for_load_spec(
            binary.sleigh_language_id(),
            compiler_id.as_deref(),
            Some(&binary.format),
            binary.is_64bit,
        );

        if db_set.databases.is_empty() {
            return;
        }

        self.ingest_signature_matches_with_databases(binary, &db_set.databases);
    }

    /// The per-function decode/hash/lookup loop, split out from
    /// [`Self::ingest_signature_matches`] so tests can exercise it against a
    /// synthetic, in-memory [`FidbfDatabase`] instead of needing a real
    /// bundled `.fidbf` file whose exact hash happens to match a real
    /// compiled binary (FID hashes are extremely build-specific -- see
    /// `PROJECT.md`'s FID entries for how brittle a real end-to-end match
    /// is to prove without knowing a database's exact source toolchain).
    fn ingest_signature_matches_with_databases(
        &mut self,
        binary: &LoadedBinary,
        databases: &[fission_signatures::fidbf::FidbfDatabase],
    ) {
        let Some(load_spec) = binary.load_spec() else {
            return;
        };
        let Ok(frontend) = RuntimeSleighFrontend::new_for_load_spec(load_spec) else {
            return;
        };
        let Some(register_model) = register_model_for_language(load_spec.pair.language_id.as_str())
        else {
            return;
        };
        let resolve_register_offset = |name: &str| -> Option<i64> {
            register_model
                .lookup_name(name)
                .map(|(offset, _size)| offset as i64)
        };

        for func in &binary.functions {
            // Skip imports/exports and already resolved PDB/Dwarf metadata
            let has_strong_name =
                func.is_import || func.is_export || self.pdb_functions.contains_key(&func.address);
            if has_strong_name {
                continue;
            }

            let max_bytes = function_max_bytes(binary, func.address, 4096);
            let Some(bytes) = binary.view_bytes(func.address, max_bytes) else {
                continue;
            };
            let memory_context = decode_memory_context_for(binary, func.address, max_bytes);
            let contract = DecodeContract::decomp_function(FID_INSTRUCTION_LIMIT);
            let Ok(decoded) = frontend.lift_raw_pcode_function_with_context_and_memory_context(
                bytes,
                func.address,
                contract,
                &memory_context,
                None,
            ) else {
                continue;
            };

            let Some((_full_count, full_hash, _specific_count, specific_hash)) =
                frontend.fid_hashes(&decoded.instructions, &resolve_register_offset)
            else {
                continue;
            };

            let best_match = databases
                .iter()
                .flat_map(|db| db.identify_by_hashes(full_hash, specific_hash))
                .max_by(|a, b| a.score.total_cmp(&b.score));

            if let Some(best_match) = best_match {
                // Ingest matched name fact with tiered priority: FactProvenance::StrongFid
                self.ingest_name_fact(func.address, best_match.name, FactProvenance::StrongFid);
            }
        }
    }

    pub fn ingest_calling_convention(&mut self, address: u64, cc: fission_core::CallingConvention) {
        self.calling_conventions.insert(address, cc);
    }

    pub fn ingest_name_fact(&mut self, address: u64, name: String, provenance: FactProvenance) {
        let trimmed = name.trim();
        if trimmed.is_empty() {
            return;
        }

        let fact = NameFact {
            name: trimmed.to_string(),
            provenance,
        };
        let facts = self.name_facts.entry(address).or_default();
        if !facts.iter().any(|current| current == &fact) {
            facts.push(fact);
        }
    }

    pub fn clear_name_facts_by_provenance(&mut self, address: u64, provenance: FactProvenance) {
        let Some(facts) = self.name_facts.get_mut(&address) else {
            return;
        };
        facts.retain(|fact| fact.provenance != provenance);
        if facts.is_empty() {
            self.name_facts.remove(&address);
        }
    }

    pub fn ingest_native_function_types(&mut self, address: u64, types: Vec<InferredTypeInfo>) {
        if types.is_empty() {
            return;
        }
        self.native_type_facts.insert(address, types);
    }

    pub fn resolved_name(&self, address: u64) -> Option<&str> {
        self.chosen_name_fact(address)
            .map(|fact| fact.name.as_str())
    }

    pub fn chosen_name_fact(&self, address: u64) -> Option<&NameFact> {
        self.name_facts
            .get(&address)?
            .iter()
            .max_by_key(|fact| name_fact_priority(fact.provenance))
    }

    pub fn iter_resolved_name_facts(&self) -> impl Iterator<Item = (u64, &NameFact)> + '_ {
        self.name_facts
            .iter()
            .filter_map(|(address, _)| self.chosen_name_fact(*address).map(|fact| (*address, fact)))
    }

    pub fn merged_inferred_types(&self, address: u64) -> Vec<InferredTypeInfo> {
        merge_type_fact_layers(
            self.native_type_facts
                .get(&address)
                .cloned()
                .unwrap_or_default(),
            self.loader_type_facts.as_ref().clone(),
        )
    }

    pub fn loader_type_facts(&self) -> &[InferredTypeInfo] {
        self.loader_type_facts.as_slice()
    }

    pub fn dwarf_function(&self, address: u64) -> Option<&DwarfFunctionInfo> {
        self.dwarf_functions.get(&address)
    }

    pub fn pdb_function(&self, address: u64) -> Option<&PdbFunctionInfo> {
        self.pdb_functions.get(&address)
    }

    pub fn preferred_debug_function(&self, address: u64) -> Option<&DwarfFunctionInfo> {
        self.dwarf_functions
            .get(&address)
            .or_else(|| self.pdb_functions.get(&address))
    }

    /// Record function-level hints discovered during structuring or normalize.
    ///
    /// Called by NIR structuring passes when they discover parameter count,
    /// local layout, or return information from the CFG. Analysis-produced
    /// hints stay in their own overlay and never impersonate DWARF/PDB records.
    ///
    /// ## Invariant
    /// Only call this when the hints represent a structural invariant (e.g.
    /// dominance-based parameter detection), not a function-specific heuristic.
    /// See the anti-overfitting architecture contract in `nir/pass/manager.rs`.
    pub fn record_structuring_hints(
        &mut self,
        address: u64,
        hints: fission_midend_core::NirFunctionHints,
    ) {
        self.structuring_hints
            .entry(address)
            .and_modify(|current| merge_structuring_hints(current, &hints))
            .or_insert(hints);
    }

    pub fn structuring_hints(
        &self,
        address: u64,
    ) -> Option<&fission_midend_core::NirFunctionHints> {
        self.structuring_hints.get(&address)
    }

    pub fn function_facts_snapshot(&self, address: u64) -> FunctionFacts {
        let mut type_facts = self
            .native_type_facts
            .get(&address)
            .into_iter()
            .flatten()
            .cloned()
            .map(|info| TypeFact {
                info,
                provenance: FactProvenance::NativeMetadata,
            })
            .collect::<Vec<_>>();
        type_facts.extend(self.loader_type_facts.iter().cloned().map(|info| TypeFact {
            info,
            provenance: FactProvenance::LoaderMetadata,
        }));

        FunctionFacts {
            address,
            chosen_name: self.chosen_name_fact(address).cloned(),
            name_facts: self.name_facts.get(&address).cloned().unwrap_or_default(),
            type_facts,
            dwarf_info: self.dwarf_functions.get(&address).cloned(),
            pdb_info: self.pdb_functions.get(&address).cloned(),
            structuring_hints: self.structuring_hints.get(&address).cloned(),
            calling_convention: self.calling_conventions.get(&address).cloned(),
        }
    }
}

fn merge_structuring_hints(
    current: &mut fission_midend_core::NirFunctionHints,
    incoming: &fission_midend_core::NirFunctionHints,
) {
    if current.param_names.len() < incoming.param_names.len() {
        current
            .param_names
            .resize(incoming.param_names.len(), String::new());
    }
    for (index, name) in incoming.param_names.iter().enumerate() {
        if current.param_names[index].is_empty() && !name.is_empty() {
            current.param_names[index] = name.clone();
        }
    }
    for (index, type_name) in &incoming.param_type_names {
        current
            .param_type_names
            .entry(*index)
            .or_insert_with(|| type_name.clone());
    }
    for (offset, name) in &incoming.stack_local_names {
        current
            .stack_local_names
            .entry(*offset)
            .or_insert_with(|| name.clone());
    }
    for (offset, type_name) in &incoming.stack_local_type_names {
        current
            .stack_local_type_names
            .entry(*offset)
            .or_insert_with(|| type_name.clone());
    }
    if current.return_type_name.is_none() {
        current
            .return_type_name
            .clone_from(&incoming.return_type_name);
    }
}

pub fn log_type_diag(
    address: u64,
    function_types: &[InferredTypeInfo],
    loader_types: &[InferredTypeInfo],
    merged_types: &[InferredTypeInfo],
) {
    if std::env::var_os("FISSION_TYPE_DIAG").is_none() {
        return;
    }

    let count_fields =
        |items: &[InferredTypeInfo]| -> usize { items.iter().map(|ty| ty.fields.len()).sum() };
    let sample_names = |items: &[InferredTypeInfo]| -> String {
        items
            .iter()
            .take(5)
            .map(|ty| ty.name.as_str())
            .filter(|name| !name.is_empty())
            .collect::<Vec<_>>()
            .join(", ")
    };

    eprintln!(
        "[TYPE-DIAG] addr=0x{:x} function_types={} function_fields={} loader_types={} loader_fields={} merged_types={} merged_fields={} samples=[{}]",
        address,
        function_types.len(),
        count_fields(function_types),
        loader_types.len(),
        count_fields(loader_types),
        merged_types.len(),
        count_fields(merged_types),
        sample_names(merged_types),
    );
}

fn name_fact_priority(provenance: FactProvenance) -> u8 {
    match provenance {
        FactProvenance::UserRename => 100,
        FactProvenance::ImportExport => 90,
        FactProvenance::PdbMetadata => 85,
        FactProvenance::StrongFid => 82,
        FactProvenance::BinarySymbol => 80,
        FactProvenance::WeakAutogenerated => 10,
        FactProvenance::NativeMetadata
        | FactProvenance::LoaderMetadata
        | FactProvenance::DebugInfo => 0,
    }
}

fn inferred_type_identity(ty: &InferredTypeInfo) -> (&str, u64, &str) {
    (&ty.name, ty.metadata_address, &ty.mangled_name)
}

fn merge_type_fields(existing: &mut Vec<InferredFieldInfo>, incoming: Vec<InferredFieldInfo>) {
    for field in incoming {
        if let Some(current) = existing
            .iter_mut()
            .find(|current| current.offset == field.offset)
        {
            if current.name.is_empty() && !field.name.is_empty() {
                current.name = field.name.clone();
            }
            if current.type_name.is_empty() && !field.type_name.is_empty() {
                current.type_name = field.type_name.clone();
            }
            if current.size == 0 && field.size != 0 {
                current.size = field.size;
            }
            continue;
        }
        existing.push(field);
    }
}

fn merge_type_fact_layers(
    function_types: Vec<InferredTypeInfo>,
    loader_types: Vec<InferredTypeInfo>,
) -> Vec<InferredTypeInfo> {
    let mut merged = Vec::new();

    for ty in function_types.into_iter().chain(loader_types.into_iter()) {
        if let Some(existing) = merged.iter_mut().find(|current| {
            let (name, metadata_address, mangled_name) = inferred_type_identity(current);
            let (incoming_name, incoming_metadata, incoming_mangled) = inferred_type_identity(&ty);
            metadata_address != 0 && incoming_metadata != 0 && metadata_address == incoming_metadata
                || (!mangled_name.is_empty()
                    && !incoming_mangled.is_empty()
                    && mangled_name == incoming_mangled)
                || (!name.is_empty() && !incoming_name.is_empty() && name == incoming_name)
        }) {
            if existing.kind.is_empty() && !ty.kind.is_empty() {
                existing.kind = ty.kind.clone();
            }
            if existing.mangled_name.is_empty() && !ty.mangled_name.is_empty() {
                existing.mangled_name = ty.mangled_name.clone();
            }
            if existing.metadata_address == 0 && ty.metadata_address != 0 {
                existing.metadata_address = ty.metadata_address;
            }
            if existing.size == 0 && ty.size != 0 {
                existing.size = ty.size;
            }
            merge_type_fields(&mut existing.fields, ty.fields);
            continue;
        }
        merged.push(ty);
    }

    merged
}

#[cfg(test)]
mod tests {
    use super::*;
    use fission_loader::loader::types::{DwarfLocalVar, DwarfLocation, DwarfParamInfo};
    use fission_loader::loader::{DataBuffer, FunctionInfo, LoadedBinaryBuilder, SectionInfo};
    use fission_signatures::fidbf::{FidbfDatabase, FidbfFunction, FidbfLibrary};

    /// Serialize tests that construct a `RuntimeSleighFrontend` -- mirrors
    /// `function_discovery::tests::sleigh_runtime_discovery_lock`, whose doc
    /// comment notes parallel-harness flakes from concurrent x86-64 decode
    /// init.
    fn sleigh_runtime_facts_lock() -> std::sync::MutexGuard<'static, ()> {
        static LOCK: std::sync::OnceLock<std::sync::Mutex<()>> = std::sync::OnceLock::new();
        LOCK.get_or_init(|| std::sync::Mutex::new(()))
            .lock()
            .unwrap_or_else(|poisoned| poisoned.into_inner())
    }

    /// End-to-end proof that `ingest_signature_matches_with_databases` --
    /// the SLEIGH-based FID replacement for the old, broken
    /// `fission_signatures::fid` hash/decoder pipeline -- actually turns a
    /// hash match into a `StrongFid` name fact. A real bundled `.fidbf`
    /// database's hashes are far too build-specific to reliably reproduce
    /// from a freshly compiled test binary (every attempt this session
    /// against real databases came back "no match", expected per FID's own
    /// design -- see `PROJECT.md`), so this uses a synthetic in-memory
    /// database instead, seeded with the exact full hash
    /// (`0x37783a7364fbdfe5`) already validated byte-for-byte against real
    /// Ghidra 12.0.4 for `55 48 89 e5 b8 2a 00 00 00 5d c3` (`push rbp; mov
    /// rbp,rsp; mov eax,0x2a; pop rbp; ret`) in
    /// `fission-sleigh`'s `fid_full_hash_matches_ghidra_exactly_for_register_only_function`.
    #[test]
    fn fid_signature_match_ingests_strong_fid_name_fact() {
        let _lock = sleigh_runtime_facts_lock();

        let func_bytes: [u8; 11] = [
            0x55, 0x48, 0x89, 0xE5, 0xB8, 0x2A, 0x00, 0x00, 0x00, 0x5D, 0xC3,
        ];
        let mut bytes = vec![0xCCu8; 0x1000];
        bytes[0x100..0x100 + func_bytes.len()].copy_from_slice(&func_bytes);

        let mut binary =
            LoadedBinaryBuilder::new("fid_test.bin".to_string(), DataBuffer::Heap(bytes))
                .format("ELF")
                .image_base(0x400000)
                .entry_point(0x401100)
                .arch_spec("x86:LE:64:default")
                .is_64bit(true)
                .add_section(SectionInfo {
                    name: ".text".to_string(),
                    virtual_address: 0x401000,
                    virtual_size: 0x1000,
                    file_offset: 0,
                    file_size: 0x1000,
                    is_executable: true,
                    is_readable: true,
                    is_writable: false,
                })
                .build()
                .expect("synthetic binary");
        binary.functions = vec![FunctionInfo {
            address: 0x401100,
            name: "sub_401100".to_string(),
            size: func_bytes.len() as u64,
            is_import: false,
            is_export: false,
            ..Default::default()
        }];

        // specific_hash deliberately doesn't match the query's (always 0,
        // since the specific hash isn't implemented yet) -- proves the
        // realistic no-bonus path, not an accidental 0==0 coincidence.
        let database = FidbfDatabase::new(
            "synthetic".to_string(),
            vec![FidbfLibrary {
                key: 1,
                family_name: "synthetic_libc".to_string(),
                version: "1.0".to_string(),
                variant: String::new(),
                ghidra_version: "12.0.4".to_string(),
                language_id: "x86:LE:64:default".to_string(),
                language_version: 1,
                language_minor_version: 0,
                compiler_spec_id: "gcc".to_string(),
            }],
            vec![FidbfFunction {
                key: 1,
                library_id: 1,
                name: "known_prologue".to_string(),
                full_hash: 0x37783a7364fbdfe5,
                specific_hash: 0xdead_beef,
                code_unit_size: 20, // clears FID_ACCEPT_THRESHOLD on its own
                entry_point: 0,
                has_terminator: true,
                specific_hash_additional_size: 0,
                domain_path: String::new(),
                flags: 0,
                auto_pass: false,
                auto_fail: false,
                force_specific: false,
                force_relation: false,
            }],
            vec![],
        );

        let mut store = FactStore::default();
        store.ingest_signature_matches_with_databases(&binary, std::slice::from_ref(&database));

        assert_eq!(store.resolved_name(0x401100), Some("known_prologue"));
        assert_eq!(
            store.chosen_name_fact(0x401100).map(|f| f.provenance),
            Some(FactProvenance::StrongFid)
        );
    }

    fn inferred_type(
        name: &str,
        metadata_address: u64,
        fields: Vec<(&str, u32)>,
    ) -> InferredTypeInfo {
        InferredTypeInfo {
            name: name.to_string(),
            mangled_name: String::new(),
            kind: "struct".to_string(),
            fields: fields
                .into_iter()
                .map(|(field, offset)| InferredFieldInfo {
                    name: field.to_string(),
                    type_name: "int".to_string(),
                    offset,
                    size: 4,
                })
                .collect(),
            size: 0,
            metadata_address,
        }
    }

    #[test]
    fn manual_name_wins_over_other_sources() {
        let mut store = FactStore::default();
        store.ingest_name_fact(0x401000, "KnownApi".into(), FactProvenance::StrongFid);
        store.ingest_name_fact(0x401000, "UserChosen".into(), FactProvenance::UserRename);
        assert_eq!(store.resolved_name(0x401000), Some("UserChosen"));
    }

    #[test]
    fn metadata_type_fields_win_over_loader_fields() {
        let mut store = FactStore {
            loader_type_facts: Arc::new(vec![inferred_type(
                "Widget",
                0,
                vec![("loader_field", 4)],
            )]),
            ..FactStore::default()
        };
        store.ingest_native_function_types(
            0x401000,
            vec![inferred_type("Widget", 0x1234, vec![("metadata_field", 4)])],
        );

        let merged = store.merged_inferred_types(0x401000);
        assert_eq!(merged.len(), 1);
        assert_eq!(merged[0].fields[0].name, "metadata_field");
    }

    #[test]
    fn snapshot_carries_chosen_name_and_dwarf_info() {
        let mut store = FactStore::default();
        store.ingest_name_fact(
            0x401000,
            "sub_401000".into(),
            FactProvenance::WeakAutogenerated,
        );
        store.ingest_name_fact(0x401000, "KnownName".into(), FactProvenance::BinarySymbol);
        Arc::make_mut(&mut store.dwarf_functions).insert(
            0x401000,
            DwarfFunctionInfo {
                address: 0x401000,
                name: "KnownName".into(),
                return_type: Some("int".into()),
                params: Vec::new(),
                local_vars: Vec::new(),
                size: 0,
            },
        );

        let snapshot = store.function_facts_snapshot(0x401000);
        assert_eq!(
            snapshot.chosen_name.as_ref().map(|fact| fact.name.as_str()),
            Some("KnownName")
        );
        assert!(snapshot.dwarf_info.is_some());
    }

    #[test]
    fn snapshot_counts_native_and_loader_type_facts_separately() {
        let mut store = FactStore {
            loader_type_facts: Arc::new(vec![inferred_type("LoaderType", 0, vec![])]),
            ..FactStore::default()
        };
        store.ingest_native_function_types(
            0x401000,
            vec![inferred_type("NativeType", 0x1234, vec![])],
        );

        let snapshot = store.function_facts_snapshot(0x401000);
        assert_eq!(snapshot.native_type_fact_count(), 1);
        assert_eq!(snapshot.loader_type_fact_count(), 1);
    }

    #[test]
    fn snapshot_counts_dwarf_type_facts_from_function_info() {
        let mut store = FactStore::default();
        Arc::make_mut(&mut store.dwarf_functions).insert(
            0x401000,
            DwarfFunctionInfo {
                address: 0x401000,
                name: "main".into(),
                return_type: Some("int".into()),
                params: vec![DwarfParamInfo {
                    name: "argc".into(),
                    type_name: "int".into(),
                    location: DwarfLocation::Unknown,
                }],
                local_vars: vec![DwarfLocalVar {
                    name: "tmp".into(),
                    type_name: "int".into(),
                    location: DwarfLocation::Unknown,
                    scope: None,
                }],
                size: 0,
            },
        );

        let snapshot = store.function_facts_snapshot(0x401000);
        assert_eq!(snapshot.dwarf_type_fact_count(), 3);
        assert_eq!(snapshot.pdb_type_fact_count(), 0);
    }

    #[test]
    fn fact_stores_share_the_same_program_snapshot() {
        use fission_loader::{FunctionInfo, loader::DataBuffer};

        let binary = fission_loader::loader::LoadedBinaryBuilder::new(
            "fixture.exe".into(),
            DataBuffer::Heap(vec![]),
        )
        .add_function(FunctionInfo {
            name: "known_function".into(),
            address: 0x401000,
            size: 8,
            ..FunctionInfo::default()
        })
        .build()
        .expect("build fixture");
        let program = Arc::new(ProgramSnapshot::from_loaded_binary(&binary));
        let first = FactStore::from_program(&binary, Arc::clone(&program));
        let second = FactStore::from_program(&binary, Arc::clone(&program));
        let first_program = first.program_arc();
        let second_program = second.program_arc();

        assert!(Arc::ptr_eq(&first_program, &second_program));
        assert_eq!(first.resolved_name(0x401000), Some("known_function"));
    }

    #[test]
    fn structuring_hints_do_not_replace_debug_metadata() {
        let mut store = FactStore::default();
        Arc::make_mut(&mut store.dwarf_functions).insert(
            0x401000,
            DwarfFunctionInfo {
                address: 0x401000,
                name: "debug_name".into(),
                return_type: Some("int".into()),
                params: vec![DwarfParamInfo {
                    name: "debug_param".into(),
                    type_name: "int".into(),
                    location: DwarfLocation::Unknown,
                }],
                local_vars: Vec::new(),
                size: 0,
            },
        );
        store.record_structuring_hints(
            0x401000,
            fission_midend_core::NirFunctionHints {
                param_names: vec!["structural_0".into(), "structural_1".into()],
                return_type_name: Some("uint32_t".into()),
                ..Default::default()
            },
        );
        store.record_structuring_hints(
            0x401000,
            fission_midend_core::NirFunctionHints {
                stack_local_names: HashMap::from([(-8, "recovered_local".into())]),
                ..Default::default()
            },
        );

        assert_eq!(
            store.preferred_debug_function(0x401000).unwrap().params[0].name,
            "debug_param"
        );
        assert_eq!(
            store.structuring_hints(0x401000).unwrap().param_names,
            ["structural_0", "structural_1"]
        );
        assert_eq!(
            store.structuring_hints(0x401000).unwrap().stack_local_names[&-8],
            "recovered_local"
        );
        let snapshot = store.function_facts_snapshot(0x401000);
        assert!(snapshot.dwarf_info.is_some());
        assert!(snapshot.structuring_hints.is_some());
    }

    #[test]
    fn test_load_sidecar_user_renames() {
        use fission_loader::loader::types::{DataBuffer, LoadedBinaryInner};
        use std::collections::HashMap;
        use std::fs;
        use std::sync::Arc;

        let binary_path = std::env::temp_dir().join("fission_test_bin_sidecar.exe");
        fs::write(&binary_path, b"mock").unwrap();

        let sidecar_path = binary_path.with_extension("fission.json");
        let sidecar_json = serde_json::json!({
            "binary_path": binary_path.display().to_string(),
            "user_function_names": {
                "4198400": "custom_name_from_sidecar",
                "0x402000": "hex_name_from_sidecar"
            }
        });
        fs::write(&sidecar_path, serde_json::to_string(&sidecar_json).unwrap()).unwrap();

        let inner = LoadedBinaryInner {
            path: binary_path.display().to_string(),
            hash: "123".to_string(),
            data: Arc::new(DataBuffer::Heap(vec![])),
            arch_spec: "x86:LE:64:default".to_string(),
            load_spec: None,
            architecture: None,
            entry_point: 0,
            image_base: 0,
            functions: Vec::new(),
            sections: Vec::new(),
            is_64bit: true,
            format: "PE".to_string(),
            iat_symbols: HashMap::new(),
            global_symbols: HashMap::new(),
            global_symbol_sizes: HashMap::new(),
            relocation_symbols: HashMap::new(),
            function_addr_index: HashMap::new(),
            function_name_index: HashMap::new(),
            functions_sorted: true,
            inferred_types: Vec::new(),
            string_map: HashMap::new(),
            pdb_debug_info: None,
            relocations: Vec::new(),
            rich_header_records: None,
            symbol_versions: HashMap::new(),
            cfg_label_leaders: Vec::new(),
        };
        let binary = LoadedBinary::from_inner(inner);
        let store = FactStore::from_binary(&binary);

        assert_eq!(
            store.resolved_name(4198400),
            Some("custom_name_from_sidecar")
        );
        assert_eq!(store.resolved_name(0x402000), Some("hex_name_from_sidecar"));

        let _ = fs::remove_file(binary_path);
        let _ = fs::remove_file(sidecar_path);
    }
}
