use fission_loader::loader::LoadedBinary;
use fission_loader::loader::types::{
    DwarfFunctionInfo, InferredFieldInfo, InferredTypeInfo, PdbFunctionInfo,
};
use fission_pcode::PreviewTypeContext;
use std::collections::HashMap;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum FactProvenance {
    UserRename,
    BinarySymbol,
    ImportExport,
    StrongFid,
    CrossImageImportExport,
    CrossImageThunk,
    WeakAutogenerated,
    PdbMetadata,
    NativeMetadata,
    LoaderMetadata,
    DebugInfo,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct NameFact {
    pub name: String,
    pub provenance: FactProvenance,
}

#[derive(Debug, Clone)]
pub struct TypeFact {
    pub info: InferredTypeInfo,
    pub provenance: FactProvenance,
}

#[derive(Debug, Clone)]
pub struct FunctionFacts {
    pub address: u64,
    pub chosen_name: Option<NameFact>,
    pub name_facts: Vec<NameFact>,
    pub type_facts: Vec<TypeFact>,
    pub dwarf_info: Option<DwarfFunctionInfo>,
    pub pdb_info: Option<PdbFunctionInfo>,
}

impl FunctionFacts {
    pub fn dwarf_type_fact_count(&self) -> usize {
        let Some(info) = self.dwarf_info.as_ref() else {
            return 0;
        };
        info.params.len() + info.local_vars.len() + usize::from(info.return_type.is_some())
    }

    pub fn pdb_type_fact_count(&self) -> usize {
        let Some(info) = self.pdb_info.as_ref() else {
            return 0;
        };
        info.params.len() + info.local_vars.len() + usize::from(info.return_type.is_some())
    }

    pub fn native_type_fact_count(&self) -> usize {
        self.type_facts
            .iter()
            .filter(|fact| fact.provenance == FactProvenance::NativeMetadata)
            .count()
    }

    pub fn loader_type_fact_count(&self) -> usize {
        self.type_facts
            .iter()
            .filter(|fact| fact.provenance == FactProvenance::LoaderMetadata)
            .count()
    }
}

#[derive(Debug, Clone, Default)]
pub struct FactStore {
    name_facts: HashMap<u64, Vec<NameFact>>,
    native_type_facts: HashMap<u64, Vec<InferredTypeInfo>>,
    loader_type_facts: Vec<InferredTypeInfo>,
    dwarf_functions: HashMap<u64, DwarfFunctionInfo>,
    pdb_functions: HashMap<u64, PdbFunctionInfo>,
}

impl FactStore {
    pub fn from_binary(binary: &LoadedBinary) -> Self {
        let mut store = Self {
            name_facts: HashMap::new(),
            native_type_facts: HashMap::new(),
            loader_type_facts: binary.inferred_types.clone(),
            dwarf_functions: binary.dwarf_functions.clone(),
            pdb_functions: binary.pdb_functions.clone(),
        };

        for func in &binary.functions {
            if is_weak_name(&func.name) {
                continue;
            }
            let provenance = if func.is_import || func.is_export {
                FactProvenance::ImportExport
            } else {
                FactProvenance::BinarySymbol
            };
            store.ingest_name_fact(func.address, func.name.clone(), provenance);
        }

        for (addr, name) in &binary.inner().iat_symbols {
            if !name.trim().is_empty() {
                store.ingest_name_fact(*addr, name.clone(), FactProvenance::ImportExport);
            }
        }

        for (addr, name) in &binary.inner().global_symbols {
            if !name.trim().is_empty() {
                store.ingest_name_fact(*addr, name.clone(), FactProvenance::BinarySymbol);
            }
        }

        for (addr, func) in &binary.pdb_functions {
            if !is_weak_name(&func.name) {
                store.ingest_name_fact(*addr, func.name.clone(), FactProvenance::PdbMetadata);
            }
        }

        store
    }

    pub fn ingest_name_fact(&mut self, address: u64, name: String, provenance: FactProvenance) {
        let trimmed = name.trim();
        if trimmed.is_empty() {
            return;
        }

        let fact = NameFact {
            name: trimmed.to_string(),
            provenance,
        };
        let facts = self.name_facts.entry(address).or_default();
        if !facts.iter().any(|current| current == &fact) {
            facts.push(fact);
        }
    }

    pub fn clear_name_facts_by_provenance(&mut self, address: u64, provenance: FactProvenance) {
        let Some(facts) = self.name_facts.get_mut(&address) else {
            return;
        };
        facts.retain(|fact| fact.provenance != provenance);
        if facts.is_empty() {
            self.name_facts.remove(&address);
        }
    }

    pub fn ingest_native_function_types(&mut self, address: u64, types: Vec<InferredTypeInfo>) {
        if types.is_empty() {
            return;
        }
        self.native_type_facts.insert(address, types);
    }

    pub fn resolved_name(&self, address: u64) -> Option<&str> {
        self.chosen_name_fact(address)
            .map(|fact| fact.name.as_str())
    }

    pub fn chosen_name_fact(&self, address: u64) -> Option<&NameFact> {
        self.name_facts
            .get(&address)?
            .iter()
            .max_by_key(|fact| name_fact_priority(fact.provenance))
    }

    pub fn iter_resolved_name_facts(&self) -> impl Iterator<Item = (u64, &NameFact)> + '_ {
        self.name_facts
            .iter()
            .filter_map(|(address, _)| self.chosen_name_fact(*address).map(|fact| (*address, fact)))
    }

    pub fn merged_inferred_types(&self, address: u64) -> Vec<InferredTypeInfo> {
        merge_type_fact_layers(
            self.native_type_facts
                .get(&address)
                .cloned()
                .unwrap_or_default(),
            self.loader_type_facts.clone(),
        )
    }

    pub fn loader_type_facts(&self) -> &[InferredTypeInfo] {
        &self.loader_type_facts
    }

    pub fn dwarf_function(&self, address: u64) -> Option<&DwarfFunctionInfo> {
        self.dwarf_functions.get(&address)
    }

    pub fn pdb_function(&self, address: u64) -> Option<&PdbFunctionInfo> {
        self.pdb_functions.get(&address)
    }

    pub fn preferred_debug_function(&self, address: u64) -> Option<&DwarfFunctionInfo> {
        self.dwarf_functions
            .get(&address)
            .or_else(|| self.pdb_functions.get(&address))
    }

    pub fn function_facts_snapshot(&self, address: u64) -> FunctionFacts {
        let mut type_facts = self
            .native_type_facts
            .get(&address)
            .into_iter()
            .flatten()
            .cloned()
            .map(|info| TypeFact {
                info,
                provenance: FactProvenance::NativeMetadata,
            })
            .collect::<Vec<_>>();
        type_facts.extend(self.loader_type_facts.iter().cloned().map(|info| TypeFact {
            info,
            provenance: FactProvenance::LoaderMetadata,
        }));

        FunctionFacts {
            address,
            chosen_name: self.chosen_name_fact(address).cloned(),
            name_facts: self.name_facts.get(&address).cloned().unwrap_or_default(),
            type_facts,
            dwarf_info: self.dwarf_functions.get(&address).cloned(),
            pdb_info: self.pdb_functions.get(&address).cloned(),
        }
    }

    pub fn build_preview_type_context(&self, binary: &LoadedBinary) -> PreviewTypeContext {
        crate::analysis::decomp::preview_context::build_preview_type_context(binary, self, 0)
    }
}

pub fn log_type_diag(
    address: u64,
    function_types: &[InferredTypeInfo],
    loader_types: &[InferredTypeInfo],
    merged_types: &[InferredTypeInfo],
) {
    if std::env::var_os("FISSION_TYPE_DIAG").is_none() {
        return;
    }

    let count_fields =
        |items: &[InferredTypeInfo]| -> usize { items.iter().map(|ty| ty.fields.len()).sum() };
    let sample_names = |items: &[InferredTypeInfo]| -> String {
        items
            .iter()
            .take(5)
            .map(|ty| ty.name.as_str())
            .filter(|name| !name.is_empty())
            .collect::<Vec<_>>()
            .join(", ")
    };

    eprintln!(
        "[TYPE-DIAG] addr=0x{:x} function_types={} function_fields={} loader_types={} loader_fields={} merged_types={} merged_fields={} samples=[{}]",
        address,
        function_types.len(),
        count_fields(function_types),
        loader_types.len(),
        count_fields(loader_types),
        merged_types.len(),
        count_fields(merged_types),
        sample_names(merged_types),
    );
}

fn name_fact_priority(provenance: FactProvenance) -> u8 {
    match provenance {
        FactProvenance::UserRename => 100,
        FactProvenance::ImportExport => 90,
        FactProvenance::PdbMetadata => 85,
        FactProvenance::BinarySymbol => 80,
        FactProvenance::StrongFid => 70,
        FactProvenance::CrossImageImportExport => 60,
        FactProvenance::CrossImageThunk => 50,
        FactProvenance::WeakAutogenerated => 10,
        FactProvenance::NativeMetadata
        | FactProvenance::LoaderMetadata
        | FactProvenance::DebugInfo => 0,
    }
}

fn inferred_type_identity(ty: &InferredTypeInfo) -> (&str, u64, &str) {
    (&ty.name, ty.metadata_address, &ty.mangled_name)
}

fn merge_type_fields(existing: &mut Vec<InferredFieldInfo>, incoming: Vec<InferredFieldInfo>) {
    for field in incoming {
        if let Some(current) = existing
            .iter_mut()
            .find(|current| current.offset == field.offset)
        {
            if current.name.is_empty() && !field.name.is_empty() {
                current.name = field.name.clone();
            }
            if current.type_name.is_empty() && !field.type_name.is_empty() {
                current.type_name = field.type_name.clone();
            }
            if current.size == 0 && field.size != 0 {
                current.size = field.size;
            }
            continue;
        }
        existing.push(field);
    }
}

fn merge_type_fact_layers(
    function_types: Vec<InferredTypeInfo>,
    loader_types: Vec<InferredTypeInfo>,
) -> Vec<InferredTypeInfo> {
    let mut merged = Vec::new();

    for ty in function_types.into_iter().chain(loader_types.into_iter()) {
        if let Some(existing) = merged.iter_mut().find(|current| {
            let (name, metadata_address, mangled_name) = inferred_type_identity(current);
            let (incoming_name, incoming_metadata, incoming_mangled) = inferred_type_identity(&ty);
            metadata_address != 0 && incoming_metadata != 0 && metadata_address == incoming_metadata
                || (!mangled_name.is_empty()
                    && !incoming_mangled.is_empty()
                    && mangled_name == incoming_mangled)
                || (!name.is_empty() && !incoming_name.is_empty() && name == incoming_name)
        }) {
            if existing.kind.is_empty() && !ty.kind.is_empty() {
                existing.kind = ty.kind.clone();
            }
            if existing.mangled_name.is_empty() && !ty.mangled_name.is_empty() {
                existing.mangled_name = ty.mangled_name.clone();
            }
            if existing.metadata_address == 0 && ty.metadata_address != 0 {
                existing.metadata_address = ty.metadata_address;
            }
            if existing.size == 0 && ty.size != 0 {
                existing.size = ty.size;
            }
            merge_type_fields(&mut existing.fields, ty.fields);
            continue;
        }
        merged.push(ty);
    }

    merged
}

fn is_weak_name(name: &str) -> bool {
    let trimmed = name.trim();
    trimmed.is_empty()
        || trimmed.starts_with("sub_")
        || trimmed.starts_with("FUN_")
        || trimmed.starts_with("Ordinal_")
        || trimmed.starts_with("thunk_")
        || trimmed.starts_with("j_")
}

#[cfg(test)]
mod tests {
    use super::*;
    use fission_core::common::types::FunctionInfo;
    use fission_loader::loader::{DataBuffer, LoadedBinaryBuilder};
    use fission_loader::loader::types::{DwarfLocalVar, DwarfLocation, DwarfParamInfo};

    fn inferred_type(
        name: &str,
        metadata_address: u64,
        fields: Vec<(&str, u32)>,
    ) -> InferredTypeInfo {
        InferredTypeInfo {
            name: name.to_string(),
            mangled_name: String::new(),
            kind: "struct".to_string(),
            fields: fields
                .into_iter()
                .map(|(field, offset)| InferredFieldInfo {
                    name: field.to_string(),
                    type_name: "int".to_string(),
                    offset,
                    size: 4,
                })
                .collect(),
            size: 0,
            metadata_address,
        }
    }

    #[test]
    fn manual_name_wins_over_other_sources() {
        let mut store = FactStore::default();
        store.ingest_name_fact(0x401000, "KnownApi".into(), FactProvenance::StrongFid);
        store.ingest_name_fact(0x401000, "UserChosen".into(), FactProvenance::UserRename);
        assert_eq!(store.resolved_name(0x401000), Some("UserChosen"));
    }

    #[test]
    fn metadata_type_fields_win_over_loader_fields() {
        let mut store = FactStore {
            loader_type_facts: vec![inferred_type("Widget", 0, vec![("loader_field", 4)])],
            ..FactStore::default()
        };
        store.ingest_native_function_types(
            0x401000,
            vec![inferred_type("Widget", 0x1234, vec![("metadata_field", 4)])],
        );

        let merged = store.merged_inferred_types(0x401000);
        assert_eq!(merged.len(), 1);
        assert_eq!(merged[0].fields[0].name, "metadata_field");
    }

    #[test]
    fn snapshot_carries_chosen_name_and_dwarf_info() {
        let mut store = FactStore::default();
        store.ingest_name_fact(
            0x401000,
            "sub_401000".into(),
            FactProvenance::WeakAutogenerated,
        );
        store.ingest_name_fact(0x401000, "KnownName".into(), FactProvenance::BinarySymbol);
        store.dwarf_functions.insert(
            0x401000,
            DwarfFunctionInfo {
                address: 0x401000,
                name: "KnownName".into(),
                return_type: Some("int".into()),
                params: Vec::new(),
                local_vars: Vec::new(),
            },
        );

        let snapshot = store.function_facts_snapshot(0x401000);
        assert_eq!(
            snapshot.chosen_name.as_ref().map(|fact| fact.name.as_str()),
            Some("KnownName")
        );
        assert!(snapshot.dwarf_info.is_some());
    }

    #[test]
    fn snapshot_counts_native_and_loader_type_facts_separately() {
        let mut store = FactStore {
            loader_type_facts: vec![inferred_type("LoaderType", 0, vec![])],
            ..FactStore::default()
        };
        store.ingest_native_function_types(
            0x401000,
            vec![inferred_type("NativeType", 0x1234, vec![])],
        );

        let snapshot = store.function_facts_snapshot(0x401000);
        assert_eq!(snapshot.native_type_fact_count(), 1);
        assert_eq!(snapshot.loader_type_fact_count(), 1);
    }

    #[test]
    fn snapshot_counts_dwarf_type_facts_from_function_info() {
        let mut store = FactStore::default();
        store.dwarf_functions.insert(
            0x401000,
            DwarfFunctionInfo {
                address: 0x401000,
                name: "main".into(),
                return_type: Some("int".into()),
                params: vec![DwarfParamInfo {
                    name: "argc".into(),
                    type_name: "int".into(),
                    location: DwarfLocation::Unknown,
                }],
                local_vars: vec![DwarfLocalVar {
                    name: "tmp".into(),
                    type_name: "int".into(),
                    location: DwarfLocation::Unknown,
                }],
            },
        );

        let snapshot = store.function_facts_snapshot(0x401000);
        assert_eq!(snapshot.dwarf_type_fact_count(), 3);
        assert_eq!(snapshot.pdb_type_fact_count(), 0);
    }

    #[test]
    fn preview_context_prefers_stronger_name_fact_over_generated_name() {
        let binary = LoadedBinaryBuilder::new("sample.exe".to_string(), DataBuffer::Heap(vec![]))
            .format("PE")
            .is_64bit(true)
            .add_function(FunctionInfo {
                name: "sub_401000".to_string(),
                address: 0x401000,
                size: 0,
                is_export: false,
                is_import: false,
            })
            .build()
            .expect("build test binary");

        let mut store = FactStore::from_binary(&binary);
        store.ingest_name_fact(
            0x401000,
            "sub_401000".to_string(),
            FactProvenance::WeakAutogenerated,
        );
        store.ingest_name_fact(0x401000, "KnownName".to_string(), FactProvenance::StrongFid);

        let context = store.build_preview_type_context(&binary);
        assert_eq!(
            context.call_targets.get(&0x401000).map(String::as_str),
            Some("KnownName")
        );
    }

    #[test]
    fn preview_context_sanitizes_import_and_global_names() {
        let binary = LoadedBinaryBuilder::new("sample.exe".to_string(), DataBuffer::Heap(vec![]))
            .format("PE")
            .is_64bit(true)
            .add_iat_symbol(0x500000, "__imp_MessageBoxW".to_string())
            .add_global_symbol(0x600000, "foo [import]".to_string())
            .build()
            .expect("build test binary");

        let store = FactStore::from_binary(&binary);
        let context = store.build_preview_type_context(&binary);

        assert_eq!(
            context.call_targets.get(&0x500000).map(String::as_str),
            Some("MessageBoxW")
        );
        assert_eq!(
            context.call_targets.get(&0x600000).map(String::as_str),
            Some("foo")
        );
    }

    #[test]
    fn preview_context_keeps_winapi_call_param_rules() {
        let binary = LoadedBinaryBuilder::new("sample.exe".to_string(), DataBuffer::Heap(vec![]))
            .format("PE")
            .is_64bit(true)
            .build()
            .expect("build test binary");
        let store = FactStore::from_binary(&binary);

        let context = store.build_preview_type_context(&binary);
        let rule = context
            .call_param_rules
            .iter()
            .find(|rule| {
                rule.callee_name == "GetWindowRect"
                    && !rule.pointer_alias.is_empty()
                    && !rule.pointee_alias.is_empty()
                    && !rule.pointee_sizes.is_empty()
            })
            .expect("GetWindowRect preview rule");

        assert_eq!(rule.pointer_size, 8);
    }
}
