use super::*;
use fission_loader::loader::LoadedBinary;
use std::cell::RefCell;

pub(super) type BuilderCacheMap<K, V> = rustc_hash::FxHashMap<K, V>;
pub(super) type BuilderCacheSet<T> = rustc_hash::FxHashSet<T>;

#[derive(Debug)]
pub(crate) struct PreviewBuilder<'a> {
    pub(crate) pcode: &'a PcodeFunction,
    pub(crate) options: &'a MlilPreviewOptions,
    pub(crate) binary: Option<&'a LoadedBinary>,
    pub(crate) type_context: Option<&'a PreviewTypeContext>,
    pub(crate) defs: HashMap<VarnodeKey, DefSite<'a>>,
    pub(crate) def_sites: HashMap<VarnodeKey, Vec<DefSite<'a>>>,
    pub(crate) block_defs: Vec<HashMap<VarnodeKey, Vec<usize>>>,
    pub(crate) lookup_site_cache:
        RefCell<BuilderCacheMap<(Option<LoweringSite>, VarnodeKey), Option<LoweringSite>>>,
    pub(crate) peel_cache: RefCell<BuilderCacheMap<(Option<LoweringSite>, VarnodeKey), Varnode>>,
    pub(crate) terminator_cache: BuilderCacheMap<usize, LoweredTerminator>,
    pub(crate) x86_branch_recovery_attempts: usize,
    pub(crate) address_to_index: HashMap<u64, usize>,
    pub(crate) block_target_keys: Vec<u64>,
    pub(crate) target_key_to_index: HashMap<u64, usize>,
    pub(crate) layout_fallthrough: Vec<Option<usize>>,
    pub(crate) successors: Vec<Vec<usize>>,
    pub(crate) predecessors: Vec<Vec<usize>>,
    pub(crate) cfg_facts: crate::nir::structuring::CfgFactCache,
    pub(crate) dom_tree: crate::nir::structuring::DomTree,
    pub(crate) irreducible_edges: HashSet<(usize, usize)>,
    /// For virtual blocks created by node-splitting: maps virtual_idx → original pcode block idx.
    /// Empty when no splitting has been applied (all blocks are genuine pcode blocks).
    pub(crate) virtual_block_map: Vec<usize>,
    pub(crate) loop_bodies: Vec<crate::nir::structuring::loop_analysis::LoopBody>,
    pub(crate) params: BTreeMap<usize, NirBinding>,
    pub(crate) locals: BTreeMap<i64, StackSlot>,
    pub(crate) locals_next_id: StackSlotId,
    pub(crate) temps: BTreeMap<String, NirBinding>,
    pub(crate) temp_next_id: u32,
    pub(crate) materialized_vns: HashMap<MaterializedVarnodeKey, String>,
    pub(crate) call_result_bindings: HashMap<LoweringSite, String>,
    pub(crate) selector_representatives: BuilderCacheMap<(usize, u64, u64), HirExpr>,
    pub(crate) current_lowering_site: Option<LoweringSite>,
    pub(crate) register_param_aliases: HashMap<u64, usize>,
    pub(crate) stack_frame_size: i64,
    pub(crate) linear_exit_cache: BuilderCacheMap<usize, Option<LinearExit>>,
    pub(crate) linear_body_cache: BuilderCacheMap<LinearBodyCacheKey, LinearBodyCachedOutcome>,
    pub(crate) active_linear_body_keys: BuilderCacheSet<LinearBodyCacheKey>,
    pub(crate) active_conditional_tail_keys: BuilderCacheSet<ConditionalTailKey>,
    pub(crate) jump_targets_cache: Option<HashSet<u64>>,
    pub(crate) active_trace_id: Option<u64>,
    pub(crate) last_trace_id: Option<u64>,
    pub(crate) next_trace_id: u64,
    pub(crate) lowering_site_depth: usize,
    pub(crate) build_duration_ms: usize,
    pub(crate) normalize_duration_ms: usize,
    pub(crate) forced_linear_structuring_count: usize,
    pub(crate) region_linearize_structuring_count: usize,
    pub(crate) region_linearize_rejected_non_structuring_failure_count: usize,
    pub(crate) region_linearize_rejected_no_exit_count: usize,
    pub(crate) region_linearize_rejected_body_lowering_failed_count: usize,
    pub(crate) region_linearize_rejected_body_lowering_conditional_tail_exit_mismatch_count: usize,
    pub(crate) region_linearize_rejected_body_lowering_conditional_tail_no_common_follow_in_window_count:
        usize,
    pub(crate) region_linearize_rejected_body_lowering_conditional_tail_follow_beyond_window_count:
        usize,
    pub(crate) region_linearize_rejected_body_lowering_conditional_tail_side_entry_or_exit_count:
        usize,
    pub(crate) region_linearize_rejected_body_lowering_conditional_tail_complex_arm_shape_count:
        usize,
    pub(crate) region_linearize_rejected_body_lowering_conditional_tail_depth_or_budget_exhausted_count:
        usize,
    pub(crate) region_linearize_rejected_body_lowering_conditional_tail_arm_body_lowering_failed_count:
        usize,
    pub(crate) region_linearize_rejected_body_lowering_conditional_tail_one_arm_body_lowering_failed_count:
        usize,
    pub(crate) region_linearize_rejected_body_lowering_conditional_tail_both_arms_body_lowering_failed_count:
        usize,
    pub(crate) region_linearize_rejected_body_lowering_conditional_tail_follow_tail_lowering_failed_count:
        usize,
    pub(crate) region_linearize_rejected_body_lowering_conditional_tail_ambiguous_multiple_follows_count:
        usize,
    pub(crate) region_linearize_rejected_body_lowering_successor_inline_rejected_count: usize,
    pub(crate) region_linearize_rejected_body_lowering_revisit_cycle_count: usize,
    pub(crate) region_linearize_rejected_body_lowering_unsupported_terminator_count: usize,
    pub(crate) region_linearize_rejected_non_advancing_count: usize,
    pub(crate) region_linearize_rejected_irreducible_cfg_count: usize,
    pub(crate) structuring_scc_component_count: usize,
    pub(crate) structuring_irreducible_scc_count: usize,
    pub(crate) rule_block_if_no_exit_count: usize,
    pub(crate) rule_block_if_no_exit_accepted_count: usize,
    pub(crate) structuring_irreducible_header_count: usize,
    pub(crate) loop_control_explicit_reducer_count: usize,
    pub(crate) loop_control_rewrite_break_count: usize,
    pub(crate) loop_control_rewrite_continue_count: usize,
    pub(crate) loop_control_rewrite_skipped_nested_scope_count: usize,
    pub(crate) loop_while_subgraph_lowered_count: usize,
    pub(crate) loop_multi_exit_break_count: usize,
    pub(crate) loop_for_lowered_count: usize,
    pub(crate) promotion_candidate_count: usize,
    pub(crate) promoted_region_count: usize,
    pub(crate) promotion_rejected_by_shape_count: usize,
    pub(crate) promotion_rejected_by_shape_missing_terminal_join_target_count: usize,
    pub(crate) promotion_rejected_by_shape_empty_nonterminal_tail_count: usize,
    pub(crate) promotion_rejected_by_gate_count: usize,
    pub(crate) discovery_seen_guarded_tail_like_shape_count: usize,
    pub(crate) discovery_rejected_noncanonical_layout_count: usize,
    pub(crate) canonicalized_guarded_tail_shape_count: usize,
    pub(crate) canonicalization_failed_multiple_payload_entries: usize,
    pub(crate) canonicalization_failed_interleaved_join_uses: usize,
    pub(crate) canonicalization_failed_interleaved_join_uses_no_next_label_count: usize,
    pub(crate) canonicalization_failed_interleaved_join_uses_nontrivial_segment_count: usize,
    pub(crate) canonicalization_failed_nonterminal_join_label: usize,
    pub(crate) canonicalization_failed_nested_tail_escape: usize,
    pub(crate) canonicalized_interleaved_join_use_count: usize,
    pub(crate) canonicalized_local_nonfallthrough_alias_count: usize,
    pub(crate) canonicalization_failed_alias_not_fallthrough_count: usize,
    pub(crate) canonicalization_failed_alias_not_fallthrough_top_level_after_label_count: usize,
    pub(crate) canonicalization_failed_alias_not_fallthrough_nested_after_label_count: usize,
    pub(crate) canonicalization_failed_alias_has_multiple_internal_predecessors_count: usize,
    pub(crate) canonicalization_failed_alias_has_nonlocal_ref_count: usize,
    pub(crate) canonicalization_failed_alias_has_nonlocal_ref_external_before_count: usize,
    pub(crate) canonicalization_failed_alias_has_nonlocal_ref_nested_before_count: usize,
    pub(crate) canonicalization_failed_alias_has_nonlocal_ref_post_segment_ref_count: usize,
    pub(crate) canonicalization_failed_alias_body_not_trivial_count: usize,
    pub(crate) canonicalization_failed_join_has_external_ref_count: usize,
    pub(crate) canonicalization_failed_payload_crosses_join_count: usize,
    pub(crate) rejected_must_emit_label: usize,
    pub(crate) rejected_must_emit_label_surviving_middle_ref: usize,
    pub(crate) rejected_must_emit_label_surviving_external_ref: usize,
    pub(crate) rejected_must_emit_label_owner_conflict: usize,
    pub(crate) rejected_not_single_pred_succ: usize,
    pub(crate) rejected_external_entry: usize,
    pub(crate) rejected_loop_or_switch_target: usize,
    pub(crate) condition_fold_and_count: usize,
    pub(crate) condition_fold_or_count: usize,
    pub(crate) condition_fold_rejected_side_effect: usize,
    pub(crate) unsupported_indirect_control_count: usize,
    pub(crate) unsupported_indirect_call_count: usize,
    pub(crate) unsupported_external_target_count: usize,
    pub(crate) indirect_surface_preserved_count: usize,
    pub(crate) indirect_target_set_refined_count: usize,
    pub(crate) dispatcher_shape_recovered_count: usize,
    pub(crate) materialization_stabilized_count: usize,
    pub(crate) representative_downgrade_count: usize,
    pub(crate) representative_downgrade_no_aliassafe_source_count: usize,
    pub(crate) representative_downgrade_join_conflict_count: usize,
    pub(crate) dispatcher_proof_unit_count: usize,
    pub(crate) dispatcher_proof_completed_count: usize,
    pub(crate) dispatcher_proof_failed_count: usize,
    pub(crate) proof_payload_direct_emit_count: usize,
}
