//! Internal builder-side telemetry accumulator.
//!
//! This is intentionally crate-private. The public telemetry contract remains
//! the flat `NirBuildStats` shape emitted by `builder::stats`.

use std::ops::{Deref, DerefMut};

#[derive(Debug, Default)]
pub(crate) struct BuilderTelemetry {
    counters: BuilderTelemetryCounters,
}

impl Deref for BuilderTelemetry {
    type Target = BuilderTelemetryCounters;

    fn deref(&self) -> &Self::Target {
        &self.counters
    }
}

impl DerefMut for BuilderTelemetry {
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.counters
    }
}

#[derive(Debug, Default)]
pub(crate) struct BuilderTelemetryCounters {
    pub(crate) build_duration_ms: usize,
    pub(crate) normalize_duration_ms: usize,
    pub(crate) structuring_duration_ms: usize,
    pub(crate) render_duration_ms: usize,
    pub(crate) rendered_code_len: usize,
    pub(crate) max_structuring_scc_component_size: usize,
    pub(crate) mir_blockgraph_admission_enabled_count: usize,
    pub(crate) mir_blockgraph_irreducible_budget_bypass_count: usize,
    pub(crate) mir_blockgraph_extreme_budget_blocked_count: usize,
    pub(crate) procedure_summary_contracted_count: usize,
    pub(crate) procedure_summary_tail_wrapper_count: usize,
    pub(crate) procedure_summary_import_thunk_count: usize,
    pub(crate) call_target_import_resolved_count: usize,
    pub(crate) call_target_direct_symbol_resolved_count: usize,
    pub(crate) call_target_unresolved_sub_fallback_count: usize,
    pub(crate) call_target_context_missing_count: usize,
    pub(crate) call_target_exact_index_hit_count: usize,
    pub(crate) call_target_exact_index_ambiguous_count: usize,
    pub(crate) call_target_export_thunk_target_resolved_count: usize,
    pub(crate) call_target_indirect_const_resolved_count: usize,
    pub(crate) call_target_iat_slot_resolved_count: usize,
    pub(crate) call_target_indirect_load_resolved_count: usize,
    pub(crate) call_target_indirect_ptr_const_folded_count: usize,
    pub(crate) call_target_indirect_rejected_non_iat_load_count: usize,
    pub(crate) call_target_indirect_rejected_non_const_ptr_count: usize,
    pub(crate) call_target_indirect_rejected_unsupported_ptr_opcode_count: usize,
    pub(crate) call_target_indirect_rejected_ambiguous_def_count: usize,
    pub(crate) call_target_indirect_rejected_non_dominating_def_count: usize,
    pub(crate) call_target_indirect_rejected_no_def_count: usize,
    pub(crate) call_target_indirect_rejected_width_mismatch_count: usize,
    pub(crate) call_target_unresolved_no_exact_identity_count: usize,
    pub(crate) forced_linear_structuring_count: usize,
    pub(crate) structuring_force_linear_explicit_count: usize,
    pub(crate) structuring_force_linear_irreducible_budget_count: usize,
    pub(crate) structuring_force_linear_extreme_budget_count: usize,
    pub(crate) region_linearize_structuring_count: usize,
    pub(crate) region_linearize_rejected_non_structuring_failure_count: usize,
    pub(crate) region_linearize_rejected_no_exit_count: usize,
    pub(crate) region_linearize_rejected_body_lowering_failed_count: usize,
    pub(crate) region_linearize_rejected_body_lowering_conditional_tail_exit_mismatch_count: usize,
    pub(crate) region_linearize_rejected_body_lowering_conditional_tail_no_common_follow_in_window_count:
        usize,
    pub(crate) region_linearize_rejected_body_lowering_conditional_tail_follow_beyond_window_count:
        usize,
    pub(crate) region_linearize_rejected_body_lowering_conditional_tail_side_entry_or_exit_count:
        usize,
    pub(crate) region_linearize_rejected_body_lowering_conditional_tail_complex_arm_shape_count:
        usize,
    pub(crate) region_linearize_rejected_body_lowering_conditional_tail_depth_or_budget_exhausted_count:
        usize,
    pub(crate) region_linearize_rejected_body_lowering_conditional_tail_arm_body_lowering_failed_count:
        usize,
    pub(crate) region_linearize_rejected_body_lowering_conditional_tail_one_arm_body_lowering_failed_count:
        usize,
    pub(crate) region_linearize_rejected_body_lowering_conditional_tail_both_arms_body_lowering_failed_count:
        usize,
    pub(crate) region_linearize_rejected_body_lowering_conditional_tail_follow_tail_lowering_failed_count:
        usize,
    pub(crate) region_linearize_rejected_body_lowering_conditional_tail_ambiguous_multiple_follows_count:
        usize,
    pub(crate) region_linearize_rejected_body_lowering_successor_inline_rejected_count: usize,
    pub(crate) region_linearize_rejected_body_lowering_revisit_cycle_count: usize,
    pub(crate) region_linearize_rejected_body_lowering_unsupported_terminator_count: usize,
    pub(crate) region_linearize_rejected_non_advancing_count: usize,
    pub(crate) region_linearize_rejected_irreducible_cfg_count: usize,
    pub(crate) structuring_scc_component_count: usize,
    pub(crate) structuring_irreducible_scc_count: usize,
    pub(crate) rule_block_if_no_exit_count: usize,
    pub(crate) rule_block_if_no_exit_accepted_count: usize,
    pub(crate) structuring_irreducible_header_count: usize,
    pub(crate) loop_control_explicit_reducer_count: usize,
    pub(crate) loop_control_rewrite_break_count: usize,
    pub(crate) loop_control_rewrite_continue_count: usize,
    pub(crate) loop_control_rewrite_skipped_nested_scope_count: usize,
    pub(crate) loop_while_subgraph_lowered_count: usize,
    pub(crate) loop_multi_exit_break_count: usize,
    pub(crate) loop_for_lowered_count: usize,
    pub(crate) region_proof_candidate_count: usize,
    pub(crate) region_proof_completed_count: usize,
    pub(crate) region_emit_ready_failed_count: usize,
    pub(crate) blockgraph_region_candidate_count: usize,
    pub(crate) blockgraph_region_complete_count: usize,
    pub(crate) blockgraph_region_rejected_missing_follow_count: usize,
    pub(crate) blockgraph_region_rejected_must_emit_label_count: usize,
    pub(crate) blockgraph_region_rejected_middle_ref_count: usize,
    pub(crate) blockgraph_region_rejected_external_ref_count: usize,
    pub(crate) blockgraph_region_rejected_join_owner_conflict_count: usize,
    pub(crate) blockgraph_region_rejected_nonterminal_join_count: usize,
    pub(crate) blockgraph_region_rejected_follow_owner_conflict_count: usize,
    pub(crate) blockgraph_region_rejected_emit_ready_count: usize,
    pub(crate) blockgraph_region_rejected_irreducible_count: usize,
    pub(crate) conditional_region_candidate_count: usize,
    pub(crate) conditional_region_promoted_count: usize,
    pub(crate) guarded_tail_candidate_count: usize,
    pub(crate) guarded_tail_promoted_count: usize,
    pub(crate) promotion_candidate_count: usize,
    pub(crate) promoted_region_count: usize,
    pub(crate) promotion_rejected_by_shape_count: usize,
    pub(crate) promotion_rejected_by_shape_missing_terminal_join_target_count: usize,
    pub(crate) promotion_rejected_by_shape_empty_nonterminal_tail_count: usize,
    pub(crate) promotion_rejected_by_gate_count: usize,
    pub(crate) discovery_seen_guarded_tail_like_shape_count: usize,
    pub(crate) guarded_tail_rejected_missing_terminal_join_count: usize,
    pub(crate) guarded_tail_rejected_side_entry_conflict_count: usize,
    pub(crate) guarded_tail_rejected_alias_interleave_conflict_count: usize,
    pub(crate) guarded_tail_rejected_ambiguous_follow_count: usize,
    pub(crate) guarded_tail_rejected_side_effectful_callee_count: usize,
    pub(crate) guarded_tail_replacement_plan_candidate_count: usize,
    pub(crate) guarded_tail_replacement_plan_completed_count: usize,
    pub(crate) guarded_tail_replacement_plan_merge_created_count: usize,
    pub(crate) guarded_tail_replacement_plan_rejected_missing_merge_count: usize,
    pub(crate) guarded_tail_replacement_plan_rejected_unstable_read_count: usize,
    pub(crate) guarded_tail_exported_binding_count: usize,
    pub(crate) guarded_tail_replacement_read_count: usize,
    pub(crate) guarded_tail_replacement_read_rewritten_count: usize,
    pub(crate) guarded_tail_replacement_read_rejected_nondominated_count: usize,
    pub(crate) guarded_tail_replacement_read_rejected_nonremovable_op_count: usize,
    pub(crate) discovery_rejected_noncanonical_layout_count: usize,
    pub(crate) canonicalized_guarded_tail_shape_count: usize,
    pub(crate) canonicalization_failed_multiple_payload_entries: usize,
    pub(crate) canonicalization_failed_interleaved_join_uses: usize,
    pub(crate) canonicalization_failed_interleaved_join_uses_no_next_label_count: usize,
    pub(crate) canonicalization_failed_interleaved_join_uses_nontrivial_segment_count: usize,
    pub(crate) canonicalization_failed_nonterminal_join_label: usize,
    pub(crate) canonicalization_failed_nested_tail_escape: usize,
    pub(crate) canonicalized_interleaved_join_use_count: usize,
    pub(crate) canonicalized_local_nonfallthrough_alias_count: usize,
    pub(crate) canonicalization_failed_alias_not_fallthrough_count: usize,
    pub(crate) canonicalization_failed_alias_not_fallthrough_top_level_after_label_count: usize,
    pub(crate) canonicalization_failed_alias_not_fallthrough_nested_after_label_count: usize,
    pub(crate) canonicalization_failed_alias_has_multiple_internal_predecessors_count: usize,
    pub(crate) canonicalization_failed_alias_has_nonlocal_ref_count: usize,
    pub(crate) canonicalization_failed_alias_has_nonlocal_ref_external_before_count: usize,
    pub(crate) canonicalization_failed_alias_has_nonlocal_ref_nested_before_count: usize,
    pub(crate) canonicalization_failed_alias_has_nonlocal_ref_post_segment_ref_count: usize,
    pub(crate) canonicalization_failed_alias_body_not_trivial_count: usize,
    pub(crate) canonicalization_failed_join_has_external_ref_count: usize,
    pub(crate) canonicalization_failed_payload_crosses_join_count: usize,
    pub(crate) rejected_must_emit_label: usize,
    pub(crate) rejected_must_emit_label_surviving_middle_ref: usize,
    pub(crate) rejected_must_emit_label_surviving_external_ref: usize,
    pub(crate) rejected_must_emit_label_owner_conflict: usize,
    pub(crate) rejected_not_single_pred_succ: usize,
    pub(crate) rejected_external_entry: usize,
    pub(crate) rejected_loop_or_switch_target: usize,
    pub(crate) condition_fold_and_count: usize,
    pub(crate) condition_fold_or_count: usize,
    pub(crate) condition_fold_rejected_side_effect: usize,
    pub(crate) unsupported_indirect_control_count: usize,
    pub(crate) unsupported_indirect_call_count: usize,
    pub(crate) unsupported_external_target_count: usize,
    pub(crate) indirect_surface_preserved_count: usize,
    pub(crate) indirect_target_set_refined_count: usize,
    pub(crate) dispatcher_shape_recovered_count: usize,
    pub(crate) materialization_stabilized_count: usize,
    pub(crate) replacement_plan_candidate_count: usize,
    pub(crate) replacement_plan_completed_count: usize,
    pub(crate) replacement_plan_merge_binding_count: usize,
    pub(crate) replacement_plan_rejected_alias_unsafe_count: usize,
    pub(crate) replacement_plan_rejected_missing_merge_count: usize,
    pub(crate) replacement_plan_rejected_representative_root_attribution_count: usize,
    pub(crate) replacement_plan_rejected_temp_only_representative_lifecycle_count: usize,
    pub(crate) replacement_plan_rejected_dead_temp_representative_count: usize,
    pub(crate) materialization_inline_suppressed_count: usize,
    pub(crate) representative_downgrade_count: usize,
    pub(crate) representative_downgrade_no_aliassafe_source_count: usize,
    pub(crate) representative_downgrade_join_conflict_count: usize,
    pub(crate) dispatcher_proof_unit_count: usize,
    pub(crate) dispatcher_proof_completed_count: usize,
    pub(crate) dispatcher_proof_failed_count: usize,
    pub(crate) switch_emit_ready_failed_count: usize,
    pub(crate) pe_admission_profile_mismatch_count: usize,
    pub(crate) proof_payload_direct_emit_count: usize,
}
