name: License Header Check

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    license-check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Check License Header
              uses: apache/skywalking-eyes/header@v0.5.0
              with:
                  config: .github/licenserc.yaml
